# NUMPY ARRAYS

In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0, 5, 10) 
# 10 evenly spaced points between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4) 
#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(3,4)

array([[0.83923714, 0.579056  , 0.4368718 , 0.78832111],
       [0.04448563, 0.00471269, 0.33160588, 0.42796957],
       [0.56067025, 0.51536443, 0.7762871 , 0.412763  ]])

In [17]:
np.random.rand(5)

array([0.03824935, 0.260379  , 0.39272228, 0.24001806, 0.51152309])

In [18]:
np.random.randn(2)

array([0.60072233, 0.51461287])

In [19]:
np.random.randn(4,4)

array([[ 1.09826548,  0.10464823,  1.93153132,  0.98731795],
       [-0.42279076,  0.18077449, -0.03371688,  0.37063985],
       [ 0.59052558, -1.0375293 , -0.7539069 ,  0.00567413],
       [ 0.99496623,  1.9782399 ,  1.27441185, -0.18446545]])

In [20]:
np.random.randint(1, 50, 10)

array([23, 43, 14, 41, 28, 33,  7, 23,  3,  8])

In [21]:
np.random.randint(1, 100)

72

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0, 50, 10)

In [25]:
ranarr

array([11, 11, 27, 45, 23, 32, 29,  1, 43, 39])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

45

In [28]:
ranarr.min()

1

In [29]:
ranarr.argmax()

3

In [30]:
ranarr.argmin()

7

In [31]:
arr.shape

(25,)

In [32]:
arr = arr.reshape(5,5)

In [33]:
arr.shape

(5, 5)

In [34]:
arr.dtype

dtype('int32')

# NUMPY INDEXING & SELECTION

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[3]

3

In [38]:
arr[2:5]

array([2, 3, 4])

In [39]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [40]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[0:5] = 100

In [43]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr = arr[0:5]

In [47]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [48]:
slice_of_arr[:] = 99

In [49]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [50]:
arr
# This actually changed the original array!!
# Numpy does that to avoid memory issues for very big arrays. 
# It does not set copies of arrays.

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [51]:
# For a copy:
arr_copy = arr.copy()

In [52]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [53]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [54]:
arr_copy[:] = 100

In [55]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [56]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

If we simply grab a slice of an array, without making a copy of it, we are actually dealing with the original array.

In [57]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
arr_2d[0][1]

10

In [60]:
arr_2d[0]

array([ 5, 10, 15])

In [61]:
arr_2d[2,1]

40

In [62]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [63]:
arr_2d[:2, 1:]
# Slices till row 2, from column 1

array([[10, 15],
       [25, 30]])

In [64]:
arr = np.arange(1,11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
bool_arr = arr > 5

In [67]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [68]:
arr[bool_arr]
# returns only where bool_arr is TRUE

array([ 6,  7,  8,  9, 10])

In [69]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [70]:
arr[arr<3]

array([1, 2])

In [71]:
arr_2d = np.arange(50).reshape(5, 10)

In [72]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [73]:
# Grab 13, 14, 23, 24
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

# NUMPY OPERATIONS

● Array with Array <br>
● Array with Scalars <br>
● Universal Array Functions

In [74]:
arr = np.arange(0,11)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [77]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Array with Scalars

In [79]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [81]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [82]:
arr /4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ])

In [83]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

Universal Array Functions

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [85]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [86]:
np.max(arr)

10

In [87]:
arr.max()

10

In [88]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [89]:
np.log(arr)
# log(0) = -infinity

C:\Users\kushw\AppData\Local\Temp\ipykernel_132\748868419.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])